name: Awesome Documentation Build

on:
  workflow_dispatch:  # Allow manual triggers
  push:
    branches: [ master ]

jobs:
  ubuntu-build:
    name: Ubuntu Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Create build directory and run CMake
        run: |
          sudo apt-get -y update
          sudo apt-get -y install flex bison doxygen freeglut3-dev libboost-dev
          git clone https://github.com/doxygen/doxygen.git doxygen_source
          cd doxygen_source
          git fetch --all --tags --prune
          git checkout tags/Release_1_10_0 -b v1.10.0
          cmake -S . -B doxygen_build_dir -G "Unix Makefiles"
          sudo cmake --build doxygen_build_dir --target install --config Release -- -j4
          cd ..
          cmake -S . -B cmake_build_dir -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=cmake_install_dir -DCOIN_BUILD_AWESOME_DOCUMENTATION=ON
      - name: Build project
        run: |
          doxygen --version
          cmake --build cmake_build_dir --target documentation_awesome --config Release -- -j4
      - name: Deploy Awesome Dcoumentation to Github Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: cmake_build_dir/html_awesome
        if: github.event_name != 'pull_request'
